import os, re, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIRS = ["actions","forms","display","feedback","navigation","brand","illustrations","icons","flags"]
out = ["# Amar Bank DS — Component API Reference",
       "",
       "> Auto-generated from `components/**/*.d.ts` + `*.prompt.md`. Do not edit by hand — regenerate instead.",
       "> Import path (from repo root): `design-system/components/<group>/<File>.jsx` or the barrel `design-system/index.js`.",
       ""]
exports_by_file = {}
for d in DIRS:
    out += [f"## {d}/", ""]
    for dts in sorted(glob.glob(f"{ROOT}/components/{d}/*.d.ts")):
        name = os.path.basename(dts)[:-5]
        src = open(dts).read()
        names = re.findall(r"export declare (?:function|const) (\w+)", src)
        exports_by_file[f"components/{d}/{name}.jsx"] = names
        out.append(f"### {name}  ·  `components/{d}/{name}.jsx`")
        pm = f"{ROOT}/components/{d}/{name}.prompt.md"
        if os.path.exists(pm):
            body = open(pm).read().split("\n", 1)[-1].strip()
            if body: out += ["", body]
        if name in ("Flag", "Icon"):
            out += ["", f"Exports {len(names)} names — see `{os.path.relpath(dts, ROOT)}` for the full list."]
        else:
            ifaces = re.findall(r"export interface \w+ \{.*?\}\s*(?=\n(?:export|/\*\*|$))", src, re.S)
            ifaces = [re.sub(r"\s*\n\s*", " ", i).replace("{ ", "{\n  ").replace("; ", ";\n  ").replace("; }", ";\n}") for i in ifaces]
            if ifaces: out += ["", "```ts", *ifaces, "```"]
            out.append(f"Exports: {', '.join('`'+n+'`' for n in names)}")
        out.append("")
open(f"{ROOT}/COMPONENTS.md", "w").write("\n".join(out))
# barrel for hand-authored components
lines = ["// Barrel for the hand-authored Amar Bank DS components (recommended API).",
         "// Figma-generated sets (brand-sets, widget-sets, misc-sets, variants) are imported directly from their files.",
         "// Auto-generated by gen_components.py.", ""]
for f, names in exports_by_file.items():
    # flags excluded: flag-data.js was truncated on import (see okf_repository_design/products/sales_dashboard/design_system/overview.md)
    if names and "/flags/" not in f:
        lines.append(f"export {{ {', '.join(sorted(set(names)))} }} from './{f}';")
open(f"{ROOT}/index.js", "w").write("\n".join(lines) + "\n")
print(len(exports_by_file), "files")
